#!/bin/sh
# Check if there is a man page

# Copyright (C) 2006  Free Software Foundation, Inc.
#
# This file is part of Hyperbole
#
# Hyperbole is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# Hyperbole is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Hyperbole; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

man -w $1 >/dev/null 2>&1 
[ $? -ne 0 ]
result=$?
echo $result
exit $result
  
